add test for order
ECE651Group16/AI-Powered-E-Commerce-App pull request #30
Opened 2024-03-16 00:06 UTC by c6liu

2024-03-16 01:29 UTC, kckevinchenzkk approved these changes

2024-03-16 04:48 UTC, LW256 commented
My last PR modified the same parts of the code as you did and caused a merge conflict on your PR, but I have already resolved it.

2024-03-16 04:50 UTC, LW256 approved these changes

2024-03-20 03:50 UTC, kckevinchenzkk requested changes
Have some errors

2024-03-20 22:12 UTC, kckevinchenzkk approved these changes

2024-03-20 22:15 UTC, merged